# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: node_modules/.package-lock.json
          node-version: 16
      
      - name: npm install and build
        run: |
          chmod 777 node_modules/.bin/vue-cli-service
          npm install
          npm run build
      
      # - name: Upload artifact for deployment job
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: node-app
      #     path: .

      - name: build images
        run: docker build -t swr.me-east-1.myhuaweicloud.com/qyx/cae-frontend .

      - name: Login to SWR
        run: docker login -u me-east-1@EEWKRHXE5OFSDHGB6LNZ -p ${{ secrets.docker_secret }} swr.me-east-1.myhuaweicloud.com

      - name: Push to SWR
        run: docker push swr.me-east-1.myhuaweicloud.com/qyx/cae-frontend
        
